name: Earth Yoga
favicon: null
layout_spectrum: 0.23989
typography_spectrum: 0.49478
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a166f'
    - '#db261f'
    - '#f6e10a'
    - '#ffffff'
    - '#917b37'
  brandStrength: 0.6875
  lightness: 0.136431293329224
  saturation: 0.0625
  rhythmicContrast: 0.320989181753248
purpose: []
