name: Earth Yoga
favicon: null
layout_spectrum: 0.23989
typography_spectrum: 0.49478
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffcc'
    - '#000000'
    - '#999999'
    - '#996633'
    - '#336699'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
