name: Earth Yoga
favicon: null
layout_spectrum: 0.05713132582604885
typography_spectrum: 0.06369611388072371
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8266946254298091
  lightness: 0.136431293329224
  saturation: 0.19456502911634743
  rhythmicContrast: 0.320989181753248
purpose: []
