name: Earth Yoga
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49478
title: Earth Yoga
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000200'
    - '#fefefc'
    - '#cc9d45'
    - '#8f0600'
    - '#5f7eb2'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
